### ISSUE TITLE
Updating installation instructions and supported RoR versions?

### ISSUE THREAD

**Issue by DFF-fred** [vteams/open-source-billing#91] opened 2019-09-17 03:30 UTC
Hi!
Was going to test drive OpenSourceBilling but finding out the installation instruction are a bit outdated. There are recent changes in the code so I would assume the software is still maintained but what is the real status?
Thank you to clarify.

**Comment by alexanderadam** [comment] 2019-09-24 09:49
I'm obviously not a maintainer but although the project is getting frequent commits the quality of the project is questionable.

1. The maintainers [are closing the GitHub issues although the corresponding problems are still there](https://github.com/vteams/open-source-billing/issues/90).
2. Installation wise people would usually [check in `Gemfile.lock` and `.ruby-version` file](https://github.com/vteams/open-source-billing/issues/87) to gain reproducibility in installations. In this project this is not the case.
3. Even **if** the files would be checked in, it would be much easier if there would be a [Docker image available](https://github.com/vteams/open-source-billing/issues/58). Because you could simply type `docker pull vteams/open-source-billing` and would be ready to run.

If you have problems with the current instructions you might also want to ensure not to use the latest bundler version. You have to use bundler version _older_ than 2!
You can ensure it by uninstalling the installed versions and install a version smaller than 2.

```bash
$ gem uninstall bundler
$ gem install bundler -v 1.9
```

**Comment by DFF-fred** [comment] 2019-09-24 11:43
Thank you for your clarification. A bit of a shame, the UI looked nice and I liked the current dashboard (compared to what I'm using). Well...thank you but I'll skip even testing it then.

**Comment by mshahzadtariq** [comment] 2019-09-25 13:53
@DFF-fred installation instruction are updated and you can use these instructions to setup application on standard linux/ubuntu system/server. In case you are facing any issue, please report that issue or fix and make pull request

**Closed** 2020-02-13 09:53 UTC
